version: 1.0.{build}
branches:
  only:
    - master
skip_tags: true
image: Ubuntu
build_script:
  - sh: sh gradlew build
after_build:
  - sh: mkdir out
  - sh: cp build/libs/LibProductInfo-1.0-SNAPSHOT.jar out/LibProductInfo-{version}.jar
artifacts:
  - path: out
    name: LibProductInfo-{version}.jar
deploy:
  - provider: GitHub
    artifact: out/LibProductInfo-{version}.jar
    draft: false
    prerelease: false
    on:
      branch: master
      APPVEYOR_REPO_TAG: true