version: 1.0.{build}
branches:
  only:
    - master
skip_tags: true
image: Ubuntu
build_script:
  - sh: sh gradlew build
after_build:
  - sh: mkdir out
  - sh: cp build/libs/LibProductInfo-1.0-SNAPSHOT.jar out/LibProductInfo-$APPVEYOR_BUILD_VERSION.jar
artifacts:
  - path: out
    name: LibProductInfo-$(APPVEYOR_BUILD_VERSION).jar
deploy:
  - provider: GitHub
    auth_token: 44388e7ec3b2d0ad2f4224dc18083f52c7b37100
    artifact: out/LibProductInfo-$(APPVEYOR_BUILD_VERSION).jar
    draft: false
    prerelease: false
    on:
      branch: master